#!/bin/fish
#
# genhtml - Generate html and resize images
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Set website location
set websitedir $HOME/code/git/ricespo


## EXECUTE

for desktop in (ls $websitedir/assets/images/rice/full)
	# Continue if not an image
	if test -z (echo $desktop | grep -i ".jpg\|.jpeg\|.png")
		continue
	end

	set basename (echo $desktop | cut -d . -f 1)

	# Create smaller compressed images
	convert $websitedir/assets/images/rice/full/$desktop -resize 900x -filter Lanczos $websitedir/assets/images/rice/$basename.jpg ^ /dev/null

	# Output html
	echo '	<div id="border">'
	echo '		<a href="./assets/full/'$desktop'" target="_blank">'
	echo '			<span class="helper"></span><img src="./assets/images/'$basename'.jpg"/>'
	echo '		</a>'
	echo '	</div>'
	echo
end
